/**
 * GENERATED — do not edit.
 *
 * One device per equipment of the demo fixture, derived by
 * `scripts/fixture/build.ts` from showroom-fr.zip. Re-run it rather than editing
 * this file; the half of the house a fixture cannot know is in `layout.ts`.
 *
 * Device ids are the contract: `friendlyName` becomes `source_device_id`, and
 * that is what a binding resolves against. Renaming one here breaks a binding in
 * every installed instance.
 */

import type { DeviceSpec } from "./types.js";

export const GENERATED_DEVICES: DeviceSpec[] = [
  { id: "sim-air-sejour", archetype: "air_quality", room: "sejour" },
  { id: "sim-appliance-dishwasher", archetype: "metered_appliance", load: "dishwasher" },
  { id: "sim-appliance-washing-machine", archetype: "metered_appliance", load: "washing-machine" },
  { id: "sim-button-1", archetype: "button" },
  { id: "sim-button-2", archetype: "button" },
  { id: "sim-button-chambre-enfant-2-1", archetype: "button", room: "chambre-enfant-2" },
  { id: "sim-button-chambre-enfant-3-1", archetype: "button", room: "chambre-enfant-3" },
  { id: "sim-button-chambre-parents-1", archetype: "button", room: "chambre-parents" },
  { id: "sim-button-cuisine-1", archetype: "button", room: "cuisine" },
  { id: "sim-button-cuisine-2", archetype: "button", room: "cuisine" },
  { id: "sim-button-garage-1", archetype: "button", room: "garage" },
  { id: "sim-button-sejour-1", archetype: "button", room: "sejour" },
  { id: "sim-button-sejour-2", archetype: "button", room: "sejour" },
  { id: "sim-clamp-cuisine", archetype: "subload_clamp", load: "cooking" },
  { id: "sim-clamp-heat-pump", archetype: "subload_clamp", load: "heat-pump" },
  { id: "sim-clamp-pool-heat-pump", archetype: "subload_clamp", load: "pool-heat-pump" },
  { id: "sim-clamp-pool-pump", archetype: "subload_clamp", room: "piscine", load: "pool-pump" },
  { id: "sim-clamp-water-heater", archetype: "subload_clamp", load: "water-heater" },
  { id: "sim-contact-entree", archetype: "contact", room: "entree" },
  { id: "sim-contact-garage", archetype: "contact", room: "garage" },
  { id: "sim-contact-sejour", archetype: "contact", room: "sejour" },
  { id: "sim-dimmer-cuisine-1", archetype: "dimmer", room: "cuisine" },
  { id: "sim-dimmer-sejour-1", archetype: "dimmer", room: "sejour" },
  { id: "sim-dimmer-sejour-2", archetype: "dimmer", room: "sejour" },
  { id: "sim-gate-1", archetype: "gate" },
  { id: "sim-gate-garage-1", archetype: "gate", room: "garage" },
  { id: "sim-grid", archetype: "grid_clamp" },
  { id: "sim-heater-chambre-enfant-2-1", archetype: "heater", room: "chambre-enfant-2" },
  { id: "sim-heater-chambre-enfant-3-1", archetype: "heater", room: "chambre-enfant-3" },
  { id: "sim-house", archetype: "simulation" },
  { id: "sim-motion-atelier-1", archetype: "motion", room: "atelier" },
  { id: "sim-motion-atelier-2", archetype: "motion", room: "atelier" },
  { id: "sim-motion-bureau-1", archetype: "motion", room: "bureau" },
  { id: "sim-motion-bureau-2", archetype: "motion", room: "bureau" },
  { id: "sim-motion-cave-1", archetype: "motion", room: "cave" },
  { id: "sim-motion-cave-2", archetype: "motion", room: "cave" },
  { id: "sim-motion-entree-1", archetype: "motion", room: "entree" },
  { id: "sim-motion-escalier-1", archetype: "motion", room: "escalier" },
  { id: "sim-motion-garage-1", archetype: "motion", room: "garage" },
  { id: "sim-motion-garage-2", archetype: "motion", room: "garage" },
  { id: "sim-motion-garage-3", archetype: "motion", room: "garage" },
  { id: "sim-motion-garage-4", archetype: "motion", room: "garage" },
  { id: "sim-motion-lux-chambre-enfant-2-1", archetype: "motion_lux", room: "chambre-enfant-2" },
  { id: "sim-motion-lux-chambre-enfant-3-1", archetype: "motion_lux", room: "chambre-enfant-3" },
  { id: "sim-motion-lux-cuisine-1", archetype: "motion_lux", room: "cuisine" },
  { id: "sim-motion-lux-sejour-1", archetype: "motion_lux", room: "sejour" },
  { id: "sim-motion-sejour-1", archetype: "motion", room: "sejour" },
  { id: "sim-motion-sejour-2", archetype: "motion", room: "sejour" },
  { id: "sim-occupant-adulte-1", archetype: "occupant", occupant: "adulte-1" },
  { id: "sim-occupant-adulte-2", archetype: "occupant", occupant: "adulte-2" },
  { id: "sim-occupant-enfant-1", archetype: "occupant", occupant: "enfant-1" },
  { id: "sim-occupant-enfant-2", archetype: "occupant", occupant: "enfant-2" },
  { id: "sim-occupant-enfant-3", archetype: "occupant", occupant: "enfant-3" },
  { id: "sim-outdoor", archetype: "outdoor_module" },
  { id: "sim-pool-cover", archetype: "pool_cover", room: "piscine" },
  {
    id: "sim-pool-heat-pump",
    archetype: "pool_heat_pump",
    room: "piscine",
    load: "pool-heat-pump",
  },
  { id: "sim-pv", archetype: "pv" },
  { id: "sim-rain", archetype: "rain_gauge" },
  { id: "sim-relay-atelier-1", archetype: "relay", room: "atelier" },
  { id: "sim-relay-cave-1", archetype: "relay", room: "cave" },
  { id: "sim-relay-chambre-enfant-2-1", archetype: "relay", room: "chambre-enfant-2" },
  { id: "sim-relay-chambre-enfant-3-1", archetype: "relay", room: "chambre-enfant-3" },
  { id: "sim-relay-chambre-parents-1", archetype: "relay", room: "chambre-parents" },
  { id: "sim-relay-entree-1", archetype: "relay", room: "entree" },
  { id: "sim-relay-escalier-1", archetype: "relay", room: "escalier" },
  { id: "sim-relay-garage-1", archetype: "relay", room: "garage" },
  { id: "sim-relay-jardin-1", archetype: "relay", room: "jardin" },
  { id: "sim-relay-jardin-2", archetype: "relay", room: "jardin" },
  { id: "sim-relay-jardin-3", archetype: "relay", room: "jardin" },
  { id: "sim-relay-jardin-4", archetype: "relay", room: "jardin" },
  { id: "sim-relay-piscine-1", archetype: "relay", room: "piscine" },
  { id: "sim-relay-pool-pump", archetype: "relay", room: "piscine", load: "pool-pump" },
  { id: "sim-relay-sejour-1", archetype: "relay", room: "sejour" },
  { id: "sim-relay-water-heater", archetype: "relay", load: "water-heater" },
  {
    id: "sim-relay-water-heater-solar",
    archetype: "relay",
    load: "water-heater",
    solarChannel: true,
  },
  { id: "sim-shutter-bureau-1", archetype: "shutter", room: "bureau" },
  { id: "sim-shutter-chambre-enfant-1-1", archetype: "shutter", room: "chambre-enfant-1" },
  { id: "sim-shutter-chambre-enfant-3-1", archetype: "shutter", room: "chambre-enfant-3" },
  { id: "sim-shutter-chambre-parents-1", archetype: "shutter", room: "chambre-parents" },
  { id: "sim-shutter-cuisine-1", archetype: "shutter", room: "cuisine" },
  { id: "sim-shutter-cuisine-2", archetype: "shutter", room: "cuisine" },
  { id: "sim-shutter-salle-de-bain-1", archetype: "shutter", room: "salle-de-bain" },
  { id: "sim-shutter-sejour-1", archetype: "shutter", room: "sejour" },
  { id: "sim-shutter-sejour-2", archetype: "shutter", room: "sejour" },
  { id: "sim-shutter-sejour-3", archetype: "shutter", room: "sejour" },
  { id: "sim-th-probe-bureau-1", archetype: "th_probe", room: "bureau" },
  { id: "sim-thermostat-maison", archetype: "thermostat" },
  { id: "sim-thermostat-sejour", archetype: "thermostat", room: "sejour" },
  { id: "sim-valve-jardin-1", archetype: "valve", room: "jardin" },
  { id: "sim-valve-jardin-2", archetype: "valve", room: "jardin" },
  { id: "sim-wind", archetype: "wind_gauge" },
  { id: "Weather Forecast", archetype: "forecast" },
];
